name: terraform

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Terraform Version
        shell: cmd
        run: terraform version

      - name: Terraform Init
        shell: cmd
        run: terraform init

      - name: Terraform Validate
        shell: cmd
        run: terraform validate

      - name: Terraform Plan
        shell: cmd
        run: terraform plan
